Dupla: 
- Davi Henrique Caide Rosa (CD);
- Mateus de Souza Bosquine Silva (CD).

## Forma de Hessemberg
Se você se sentir à vontade, pode definir um tipo de dado para os refletores, e então as funções
desta questão poderiam receber e retornar Refletores, ao invés de v e β separadamente.

## Questão 2a)

**Enunciado:**
Aplicando refletores. Escreva uma função apply_reflector($v,\beta, b$) que calcula $Qvb$, onde $Qv = I −\beta vv∗$ é o refletor de Householder dado por v e $\beta$.

In [ ]:
import numpy as np

def apply_reflector(v, beta, b):
    produto_escalar = np.dot(v, b)
    Qb = b - (beta* produto_escalar)*v

    return Qb

## Questão 2b)

**Enunciado:** Testes. Verifique que sua função está correta, aplicando em vetores x de mesma dimen
são que v, e depois para vetores de dimensões maiores do que v (adaptando, se necessário,
sua função para funcionar neste caso). Certifique-se que sua função tem complexidade
$O(n)$, onde n é a dimensão do vetor de entrada.

In [10]:
#TESTES
def apply_reflector_adaptada(v, beta, b):
    #cópia para não sobrescrever o vetor original do usuário
    b_out = np.copy(b)
    b_resto = b_out[(len(b)-len(v)):]
    
    #aplicação da lógica APENAS nas entradas onde b tem tamanho maior que v
    produto_escalar = np.dot(v, b_resto)
    b_out[(len(b)-len(v)):] = b_resto-(beta *produto_escalar) * v
    
    return b_out

def obter_v_beta(x):
    n_x = np.linalg.norm(x)
    v = np.copy(x)
    v[0] = x[0] - n_x
    beta = 2.0 / np.dot(v, v)
    return v, beta

# CASO 1: MESMA DIMENSÃO
print("Caso 1- Vetores de mesma diemnsão \n")
#vetores
x1 = np.array([3.0, 4.0, 0.0])
b1= np.array([1.0, 2.0, 3.0])
x2 = np.array([1.5, 2.5, -3.0])
b2= np.array([-1.0, 0.5, 2.0])
x3 = np.array([1.0, -1.0, 1.0, -1.0, 1.0])
b3 = np.array([2.0, 4.0, 6.0, 8.0, 10.0])

vetores_x = [x1,x2,x3]
vetores_b = [b1,b2,b3]

for i,x in enumerate(vetores_x):
    v, beta = obter_v_beta(x)
        
    resultado_otimizado = apply_reflector_adaptada(v, beta, vetores_b[i])
    I = np.identity(len(v))
    Q_matriz = I - beta * np.outer(v, v)
    resultado_matricial = Q_matriz @ vetores_b[i]
        
    print(f"Vetor b: {vetores_b[i]}")
    print(f"Resultado O(n): {np.round(resultado_otimizado, 4)}")
    print(f"Resultado O(n^2): {np.round(resultado_matricial, 4)}")
        


    # CASO 2: DIMENSÃO MAIOR (b é maior que v)
print("\n\n\nCaso 2 - Vetores de dimensões distintas")
    
x4 = np.array([1.0, 2.0])
b4 = np.array([10.0, 20.0, 30.0, 40.0])
x5 = np.array([3.0, 4.0, 0.0])
b5 = np.array([-5.0, 7.0, 1.0, 2.0, 3.0, 4.0])
x6 = np.random.randn(4)
b6 = np.random.randn(7)

vetores_x_grande = [x4, x5, x6]
vetores_b_grande = [b4, b5, b6]

for i, x in enumerate(vetores_x_grande):
    b_grande = vetores_b_grande[i]
    v, beta = obter_v_beta(x)
        
    resultado_otimizado = apply_reflector_adaptada(v, beta, b_grande)
        
    n = len(b_grande)
    m = len(v)
    k = n - m

    I_pequena = np.identity(m)
    Q_matriz = I_pequena - beta * np.outer(v, v)
    I_grande = np.identity(n)
    I_grande[k:, k:] = Q_matriz 
        
    resultado_matricial = I_grande @ b_grande
    print(f"\n TESTE 2")
    print(f"Vetor b: {np.round(b_grande, 2)}")
    print(f"Resultado O(n):   {np.round(resultado_otimizado, 4)}")
    print(f"Resultado O(n^2): {np.round(resultado_matricial, 4)}")


Caso 1- Vetores de mesma diemnsão 

Vetor b: [1. 2. 3.]
Resultado O(n): [ 2.2 -0.4  3. ]
Resultado O(n^2): [ 2.2 -0.4  3. ]
Vetor b: [-1.   0.5  2. ]
Resultado O(n): [-1.494   0.9603  1.4477]
Resultado O(n^2): [-1.494   0.9603  1.4477]
Vetor b: [ 2.  4.  6.  8. 10.]
Resultado O(n): [2.6833 4.5528 5.4472 8.5528 9.4472]
Resultado O(n^2): [2.6833 4.5528 5.4472 8.5528 9.4472]



Caso 2 - Vetores de dimensões distintas

 TESTE 2
Vetor b: [10. 20. 30. 40.]
Resultado O(n):   [10.     20.     49.1935  8.9443]
Resultado O(n^2): [10.     20.     49.1935  8.9443]

 TESTE 2
Vetor b: [-5.  7.  1.  2.  3.  4.]
Resultado O(n):   [-5.   7.   1.   3.6 -0.2  4. ]
Resultado O(n^2): [-5.   7.   1.   3.6 -0.2  4. ]

 TESTE 2
Vetor b: [-0.27  0.65  0.8   0.06  0.46 -0.41 -0.49]
Resultado O(n):   [-0.2651  0.6474  0.8045  0.6257  0.1337 -0.4582 -0.0295]
Resultado O(n^2): [-0.2651  0.6474  0.8045  0.6257  0.1337 -0.4582 -0.0295]


### Complexidade da Função `apply_reflector_adaptada`

Considere a função

Desejamos determinar sua complexidade assintótica em função de $n$, onde $n$ representa o tamanho do vetor $v$.

#### Passo 1: Cópia do vetor

A instrução

```python
b_out = np.copy(b)
```

realiza uma cópia completa de $b$. Se considerarmos apenas a parte do algoritmo que aplica o refletor, essa operação não depende de $v$. Em aplicações típicas do algoritmo de Hessenberg, o tamanho de $b$ é proporcional ao tamanho do subproblema considerado.

#### Passo 2: Extração do trecho relevante

```python
b_resto = b_out[(len(b)-len(v)):]
```

A operação de fatiamento produz uma visão ou cópia de um trecho contendo exatamente $n$ elementos. Portanto, o custo é proporcional a $n$: $O(n)$.

#### Passo 3: Produto escalar

```python
produto_escalar = np.dot(v, b_resto)
```

O produto escalar entre dois vetores de tamanho $n$ exige:

- $n$ multiplicações;
- $n-1$ somas.

Logo, seu custo é $O(n)$.

#### Passo 4: Atualização do vetor

```python
b_resto - (beta * produto_escalar) * v
```

A expressão realiza:

1. uma multiplicação escalar de $v$ por um número;
2. uma subtração elemento a elemento.

Ambas percorrem todos os $n$ elementos do vetor, resultando em O(n)$.

A atribuição ao trecho correspondente de `b_out`

```python
b_out[(len(b)-len(v)):] = ...
```

também percorre $n$ posições, mantendo o mesmo custo assintótico.

### Complexidade Total

Somando os custos dominantes: $O(n) + O(n) + O(n) + O(n)$.

Como constantes multiplicativas são desprezadas na notação assintótica, obtemos $O(4n)=O(n)$.

## Questão 2c)

**Enunciado:** Generalize sua função para apply_reflector($v, \beta, A$) que calcula $QvA$ para uma
matriz A (com no mínimo o mesmo número de linhas do que v).

In [11]:
def apply_reflector_c(v, beta, A):
    # QA = (I - Bvv*)A = A- Bvv*A
    A_out = np.copy(A)
    m = len(v)
    k = A.shape[0]-m

    A_resto = A_out[k:, :]
    va = np.dot(v, A_resto)
    A_out[k:,:] = A_resto - beta * np.outer(v,va)

    return A_out

## Questão 2d)

**Enunciado:** Escreva uma função rev_apply_reflector($v, \beta, A$) que calcula $AQv$ (com A de
dimensões compatíveis).

In [12]:
def rev_apply_reflector(v, beta, A):
    # AQ = A(I - beta*vv*) = A - beta*(Av)v*
    A_out = np.copy(A)
    
    M, N = A.shape
    m = len(v)
    k = N - m
    A_resto = A_out[:, k:]
    
    # y = A_resto @ v
    y = A_resto @ v
    A_out[:, k:] = A_resto - beta * np.outer(y, v)
    
    return A_out

## Questão 2e)

**Enunciado:** Juntando tudo. Escreva uma função to_hessemberg(A) que calcula a forma de Hessemberg de uma matriz A usando refletores de Householder. A função deve retornar uma
lista de refletores ($v_i,\beta_i$), a matriz H tal que $A = QHQ∗$, e, opcionalmente, Q, que é a
matriz ortogonal dada pelo produto dos refletores.

In [13]:
def to_hessemberg(A):
    linhas = A.shape[0]
    H = np.copy(A)
    
    #matriz Q começa como Identidade e vai acumulando as transformações
    Q = np.identity(linhas)
    refletores=[]

    # iteramos até n-2, pois as duas últimas linhas formam um bloco 2x2 que já estão na forma de Hessenberg.
    for k in range(linhas - 2):
        x = H[k+1:, k]
        n_x = np.linalg.norm(x)
        
        if n_x <1e-12:
            continue
        
        #cálculo de v e beta
        v = np.copy(x)
        if x[0] > 0:
            y = x[1:]
            v[0] = -np.sum(np.square(y)) / (x[0] + n_x)
        else:
            v[0] = x[0] - n_x
        beta = 2.0 / np.dot(v, v)
        refletores.append((v, beta))
        
        #aplicando o refletor pela esquerda(linhas)
        H[:, k:] = apply_reflector_c(v, beta, H[:, k:])
        
        #aplicando o refletor pela direit(colunas)
        H = rev_apply_reflector(v, beta, H)

        Q = rev_apply_reflector(v, beta, Q)
    H = np.triu(H, -1)
    return refletores, H, Q

In [14]:
#APENAS UM TESTE BÁSICO
A = np.array([
        [ 2.0,  1.0,  3.0,  4.0],
        [ 5.0,  6.0,  1.0,  2.0],
        [ 9.0, -2.0,  4.0,  1.0],
        [-1.0,  3.0,  5.0,  8.0]
    ])
    
print("MATRIZ A:")
print(A)
refletores, H, Q = to_hessemberg(A)

print("\n Hessenberg:")
print(np.round(H, 4))


MATRIZ A:
[[ 2.  1.  3.  4.]
 [ 5.  6.  1.  2.]
 [ 9. -2.  4.  1.]
 [-1.  3.  5.  8.]]

 Hessenberg:
[[ 2.      2.7069  3.8254 -2.0099]
 [10.3441  3.3458  0.9922 -1.3495]
 [ 0.      5.7195  8.8826 -0.9596]
 [ 0.      0.      0.3939  5.7716]]


## Questão 2f)

**Enunciado:** Verifique que sua função de fato está correta, calculando $∥A − QHQ∗∥$ e $∥Q∗Q − I∥$ para
matrizes simétricas e não simétricas, e de tamanhos 2, 10 e 100.

In [15]:
import pandas as pd

resultados = []
tamanhos = [2, 10, 100]

for n in tamanhos:
    I_n = np.identity(n)

    # MATRIZ NÃO SIMÉTRICA
    A_nao_simetrica = np.random.randn(n, n)
    _, H_ns, Q_ns = to_hessemberg(A_nao_simetrica)

    erro_ns = np.linalg.norm(A_nao_simetrica - Q_ns @ H_ns @ Q_ns.T)
    erro_orto_ns = np.linalg.norm(Q_ns.T @ Q_ns - I_n)

    resultados.append({
        "Dimensão": n,
        "Tipo": "Não Simétrica",
        "||A - QHQ*||": erro_ns,
        "||Q*Q - I||": erro_orto_ns
    })

    # MATRIZ SIMÉTRICA
    M = np.random.randn(n, n)
    A_simetrica = M + M.T

    _, H_s, Q_s = to_hessemberg(A_simetrica)

    erro_s = np.linalg.norm(A_simetrica - Q_s @ H_s @ Q_s.T)
    erro_orto_s = np.linalg.norm(Q_s.T @ Q_s - I_n)

    resultados.append({
        "Dimensão": n,
        "Tipo": "Simétrica",
        "||A - QHQ*||": erro_s,
        "||Q*Q - I||": erro_orto_s
    })

df_resultados = pd.DataFrame(resultados)

# Exibição em notação científica
pd.set_option("display.float_format", "{:.2e}".format)

display(df_resultados)


,Dimensão,Tipo,||A - QHQ*||,||Q*Q - I||
0,2,Não Simétrica,0.00e+00,0.00e+00
1,2,Simétrica,0.00e+00,0.00e+00
2,10,Não Simétrica,7.84e-15,1.56e-15
3,10,Simétrica,8.96e-15,1.71e-15
4,100,Não Simétrica,1.37e-13,1.04e-14
5,100,Simétrica,1.71e-13,9.98e-15


### Resultados do Experimento

Para as matrizes de dimensão $2\times2$, os erros obtidos foram nulos dentro da precisão numérica da máquina. Isso ocorre porque matrizes dessa dimensão já estão naturalmente na forma de Hessenberg, não sendo necessária nenhuma transformação.

Para as matrizes de dimensões $10\times10$ e $100\times100$, os erros de reconstrução permaneceram entre $10^{-15}$ e $10^{-13}$, enquanto os erros de ortogonalidade ficaram próximos de $10^{-15}$. Esses valores são compatíveis com a precisão de máquina da aritmética `float64`, cujo epsilon de máquina é aproximadamente

$\varepsilon_{\text{mach}} \approx 2.22\times10^{-16}$.

Observa-se ainda um leve aumento do erro de reconstrução à medida que a dimensão da matriz cresce. Esse comportamento é esperado, pois cada transformação de Householder introduz pequenos erros de arredondamento que se acumulam ao longo do algoritmo. Ainda assim, os erros permanecem extremamente pequenos quando comparados à escala dos dados.

Por outro lado, a ortogonalidade da matriz $Q$ é preservada com alta precisão em todos os experimentos, apresentando erros da ordem de $10^{-15}$. Isso indica que o produto sucessivo dos refletores de Householder foi realizado de forma numericamente estável.

### Conclusão

Os resultados obtidos confirmam a corretude da implementação da decomposição de Hessenberg. Em todas as matrizes testadas, tanto simétricas quanto não simétricas, a reconstrução $QHQ^*$ reproduziu a matriz original com erro próximo da precisão de máquina, enquanto a matriz \(Q\) permaneceu ortogonal dentro da tolerância esperada para aritmética de dupla precisão.

Portanto, os experimentos fornecem evidências de que a implementação está correta e apresenta boa estabilidade numérica.